@host = http://localhost:3000
@recurso = galeria

### busca fotos e videos
GET {{host}}/{{recurso}} HTTP/1.1
content-type: application/json

### busca fotos
GET {{host}}/{{recurso}}/fotos HTTP/1.1
content-type: application/json

### busca videos
GET {{host}}/{{recurso}}/videos HTTP/1.1
content-type: application/json

### salva fotos 
POST {{host}}/{{recurso}} HTTP/1.1
content-type: application/json

{
    "src": "https://i.ibb.co/3Sc8sBq/joao-e-francisco.jpg",
    "alt": "Foto da associação.",
    "tipo": "foto"
  }


### salva  videos
POST {{host}}/{{recurso}} HTTP/1.1
content-type: application/json

{
    "src": "https://www.youtube.com/embed/WzvkmLTZhl8",
    "alt": "Vídeo não carregou!",
    "tipo": "video"
  }
 